--the dataset?
SELECT * FROM customer LIMIT 10;
--total revenue generated by male and female customer?
SELECT  gender,SUM(purchase_amount) AS revenue
FROM customer 
GROUP BY gender;
--which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied='Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);
--which are the top 5 products with the highest average review rating?
SELECT item_purchased , ROUND(AVG(review_rating::numeric),2) AS "average review rating"
FROM customer
GROUP BY item_purchased
Order by AVG(review_rating) desc
limit 5;
--compare the average purchase amounts between standard and express shipping?
SELECT shipping_type,
       ROUND(AVG(purchase_amount)::numeric,2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;
--do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers?
SELECT subscription_status,COUNT(customer_id),
ROUND(AVG(purchase_amount),2) AS avgspend,
ROUND(SUM(purchase_amount),2) AS totalrevenue
FROM customer
GROUP BY subscription_status
ORDER BY totalrevenue,avgspend;
--which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND((SUM(CASE
	                 WHEN discount_applied='Yes'
					 THEN 1
					 ELSE 0
				  END)*100)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
--segment customers into new,returning and local based on their total number of previous purchases, and show the count of each segment?
SELECT SUM(CASE
               WHEN previous_purchases=1
			   THEN 1
			   ELSE 0
			END  ) AS new,
SUM(CASE
               WHEN previous_purchases between 2 and 10
			   THEN 1
			   ELSE 0
			END  ) AS returning,
SUM(CASE
               WHEN previous_purchases > 10
			   THEN 1
			   ELSE 0
			END  ) AS loyal
from customer;			
--what are the top 3 most purchased product within each category?
WITH item_count AS(
SELECT category,item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(partition by category order by COUNT(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
from item_count
where item_rank<=3;
-- are the customers who are repeat buyers(having more than 5 purchases) aslo likely to subscribre?			
SELECT subscription_status,count(customer_id) AS repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;
--what is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by sum(purchase_amount) desc;

